export const SELECT_OPTION = 'SELECT_OPTION';
export const CLEAR_SELECTED_OPTION = 'CLEAR_SELECTED_OPTION';
export const UPDATE_TOPPING = 'UPDATE_TOPPING';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
